CREATE TABLE "BOOK" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255) NOT NULL,
    "AUTHOR" VARCHAR(255) NOT NULL,
    "PAGES" INTEGER NOT NULL,
    "COPIES" INTEGER NOT NULL
);

CREATE TABLE "CUSTOMER" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(255) NOT NULL,
    "EMAIL" VARCHAR(255) NOT NULL,
    "MEMBERSHIPPAID" BOOLEAN
);

CREATE TABLE "RENT" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CUSTOMERID" BIGINT REFERENCES CUSTOMER (ID) ON DELETE CASCADE,
    "BOOKID" BIGINT REFERENCES BOOK (ID) ON DELETE CASCADE,
    "STARTDATE" DATE,
    "EXPECTEDENDDATE" DATE,
    "REALENDDATE" DATE 
);

